version: '3'
services:

  myrabbit:
    image: rabbitmq:3-management

  mongodb:
    image: mongo:3.4-xenial

  configserver:
    image: mistborn94/cloud-stream-example/config-server:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: cloudstream
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/Mistborn94/playground.git

  source:
    image: mistborn94/cloud-stream-example/web-source:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    ports:
      - 8080:8080
    depends_on:
      - myrabbit
      - configserver

  processor:
    image: mistborn94/cloud-stream-example/processor:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    depends_on:
      - myrabbit
      - configserver

  sink:
    image: mistborn94/cloud-stream-example/sink:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    depends_on:
      - myrabbit
      - configserver
      - mongodb

  reactive-api:
    image: mistborn94/cloud-stream-example/reactive-web-api:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    ports:
      - 8081:8080
    depends_on:
      - myrabbit
      - configserver
      - mongodb

  prometheus:
    image: prom/prometheus
    volumes:
      - .:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090