server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    uri: file:///dev/playground
                    search-paths: cloud-stream-config
