apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-stream-demo
  namespace: cloud-stream-demo
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cloud-stream-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cloud-stream-demo
    namespace: cloud-stream-demo