apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    project: cloud-stream-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
        project: cloud-stream-demo
    spec:
      containers:
        - name: processor
          image: mistborn94/example-cloud-stream-processor:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap