apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink
  labels:
    project: cloud-stream-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sink
  template:
    metadata:
      labels:
        app: sink
        project: cloud-stream-demo
    spec:
      containers:
        - name: sink
          image: mistborn94/example-cloud-stream-sink:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap