apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  labels:
    project: cloud-stream-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
        project: cloud-stream-demo
    spec:
      containers:
        - name: web-api
          image: mistborn94/cloud-stream-example/reactive-web-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
  labels:
    project: cloud-stream-demo
spec:
  selector:
    app: web-api
  ports:
    - port: 8080
      nodePort: 30200
  type: NodePort