server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          searchLocations:
          - file:../cloud-stream-config
          - file:../cloud-stream-config/{application}