version: '3'
services:

  myrabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 5671:5671
      - 15671:15671
      - 15672:15672

  source:
    build:
      context: ./web-source
      dockerfile: ../Dockerfile
    environment:
      SPRING_RABBITMQ_HOST: myrabbit
    ports:
      - 8080:8080

  processor:
    build:
      context: ./processor
      dockerfile: ../Dockerfile
    environment:
      SPRING_RABBITMQ_HOST: myrabbit

  sink:
    build:
      context: ./sink
      dockerfile: ../Dockerfile
    environment:
      SPRING_RABBITMQ_HOST: myrabbit