version: '3'
services:

  myrabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 5671:5671
      - 15671:15671
      - 15672:15672

  source:
    build:
      context: ./web-source
      dockerfile: ../Dockerfile
      args:
        jar: cloud-stream-web-source-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_RABBITMQ_HOST: myrabbit
    ports:
      - 8080:8080

  sink:
    build:
      context: ./sink
      dockerfile: ../Dockerfile
      args:
        jar: cloud-stream-sink-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_RABBITMQ_HOST: myrabbit

  processor:
    build:
      context: ./processor
      dockerfile: ../Dockerfile
      args:
        jar: cloud-stream-processor-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_RABBITMQ_HOST: myrabbit