version: '3'
services:

  myrabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 5671:5671
      - 15671:15671
      - 15672:15672

  configserver:
    image: mistborn94/example-configserver
    ports:
      - 8888:8888
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/Mistborn94/playground.git

  source:
    image: mistborn94/example-cloud-stream-web-source
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    ports:
      - 8080:8080
    depends_on:
      - myrabbit
      - configserver

  processor:
    image: mistborn94/example-cloud-stream-processor
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    depends_on:
      - myrabbit
      - configserver

  sink:
    image: mistborn94/example-cloud-stream-sink
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    depends_on:
      - myrabbit
      - configserver