version: '3'
services:

  myrabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 5671:5671
      - 15671:15671
      - 15672:15672

  mongodb:
    image: mongo:3.4-xenial
    ports:
      - 27017:27017

  configserver:
    image: mistborn94/cloud-stream-example/config-server:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: cloudstream
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/Mistborn94/playground.git
    ports:
      - 8888:8888

  source:
    image: mistborn94/cloud-stream-example/web-source:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    ports:
      - 8080:8080
    depends_on:
      - myrabbit
      - configserver

  processor:
    image: mistborn94/cloud-stream-example/processor:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    depends_on:
      - myrabbit
      - configserver

  sink:
    image: mistborn94/cloud-stream-example/sink:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    depends_on:
      - myrabbit
      - configserver

  reactive-api:
    image: mistborn94/cloud-stream-example/reactive-web-api:${IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    ports:
      - 8081:8081
    depends_on:
      - myrabbit
      - configserver
      - mongodb