version: '3'
services:

  myrabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 5671:5671
      - 15671:15671
      - 15672:15672

  source:
    build:
      context: ./web-source
      dockerfile: ../Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    ports:
      - 8080:8080

  processor:
    build:
      context: ./processor
      dockerfile: ../Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888

  sink:
    build:
      context: ./sink
      dockerfile: ../Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: compose
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888

  configserver:
    build:
      context: ./config-server
      dockerfile: ../Dockerfile
    ports:
      - 8888:8888
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/Mistborn94/playground.git