spring:
  cloud:
    stream:
      bindings:
        input:
          destination: cloudstream-local.processor
        output:
          destination: cloudstream-local.sink
management:
  server:
    port: 8082