spring:
  cloud:
    stream:
      bindings:
        input:
          destination: cloudstream.processor
          group: processor
        output:
          destination: cloudstream.sink
      function:
        definition: byteToString|logMessage|trim|toUpperCase|addTimestamp
  jackson:
      mapper:
        default-view-inclusion: true
