spring:
  cloud:
    stream:
      bindings:
        input:
          group: processor
      function:
        definition: byteToString|logMessage|trim|toUpperCase|addTimestamp
  jackson:
      mapper:
        default-view-inclusion: true
# I want only the management server's port opened
server:
  port: -1
